install.packages("GISTools")
library(GISTools)
data(georgia)
appling <- georgia.polys[[1]]
plot(appling, asp = 1, type = "n", xlab = "Easting", ylab = "Northing")
polygon(appling, density = 14, angle = 135)

data(meuse.grid)
mat <- SpatialPixelsDataFrame(points = meuse.grid[c("x", "y")], data = meuse.grid)
par(mfrow = c(1, 2))
par(mar = c(0, 0, 0, 0))
image(mat, "dist")
library(RColorBrewer)
greenpal <- brewer.pal(7, "Greens")
image(mat, "dist", col = greenpal)
contour(mat, "dist")

data(newhaven)
ls()
plot(roads)
class(roads)
class(blocks)
class(tracts)
class(breach)
head(data.frame(blocks))
head(breach)
plot(blocks)
plot(roads, add = T, col = "red")
plot(breach, add = T, col = "blue")
map.scale(534750, 152000, miles2ft(3), "Miles", 4, 0.5)
north.arrow(534750, 159000, miles2ft(0.25), col = "lightgreen")
