---
title: "Map FIA"
author: "Jake Wittman"
output: html_document
---
## App Purpose
   
   The purpose of this app is to provide an easy-to-use interface for anyone who is interested in visualizing data on the distribution of tree species as well as their basal area per acre in the US. This data comes from the U.S. Forest Service Data Archive and more specifically from: 
   
   
   >Wilson, Barry Tyler; Lister, Andrew J.; Riemann, Rachel I.; Griffith, Douglas M. 2013. Live tree species basal area of the contiguous United States (2000-2009). Newtown Square, PA: USDA Forest Service, Rocky Mountain Research Station. https://doi.org/10.2737/RDS-2013-0013

This app allows the user to select one or more tree species from the  species included in this database and plot the raster data showing the predicted distribution of those tree species as well as the predicted basal area. If two or more species are selected, the user has the option to display either the combined distributions and basal areas for these species or only the areas where they co-occur (if they do at all). Users can select which of the 48 continental states they would like to plot the data. The app also provides options for the user to change the color scheme used in projecting the data to suit their preference. Download options are available too, allowing the user to download the maps they create in three different file formats (PNG, JPEG, or TIFF) and at custom DPI and dimensions.My aim with this app is to make this data more accessible to the general public, but especially researchers, foresters, managers, etc. who may find distribution data helpful for identifying research plots or addressing management issues. 
  